version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./hsystem.db
    volumes:
      - ./data:/app/data
    
  frontend:
    build: ../frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  data:
